import TabOrderActivePng from '../../assets/png/order-active.png';
import TabProductActivePng from '../../assets/png/product-active.png';
import TabInventoryActivePng from '../../assets/png/inventory-active.png';
import TabHomeActivePng from '../../assets/png/overview-active.png';
import TabOrderInActivePng from '../../assets/png/order.png';
import TabProductInActivePng from '../../assets/png/product.png';
import TabInventoryInActivePng from '../../assets/png/inventory.png';
import TabHomeInActivePng from '../../assets/png/overview.png';
import ShopDummyPng from '../../assets/png/shopdummy.png';
import ProductSearchPng from '../../assets/png/search.png';
import FashoPng from '../../assets/png/fasho-logo.png';
import SalesPosPng from '../../assets/png/sales-pos.png';
import SalesNegPng from '../../assets/png/sales-neg.png';
import VisitorsPng from '../../assets/png/visitors.png';
import StarPng from '../../assets/png/star.png';
import SettlementPng from '../../assets/png/settlement.png';
import RefundPng from '../../assets/png/refund.png';
import DangerPng from '../../assets/png/danger.png';
import NotificationPng from '../../assets/png/notification.png';
import ProfileCirclePng from '../../assets/png/profile-circle.png';
import Success_Gif from '../../assets/gif/success-arrow.gif';
import Downward_Gif from '../../assets/gif/downward.gif';

export const TabOrderActive = TabOrderActivePng;
export const TabProductActive = TabProductActivePng;
export const TabInventoryActive = TabInventoryActivePng;
export const TabHomeActive = TabHomeActivePng;
export const TabOrderInActive = TabOrderInActivePng;
export const TabProductInActive = TabProductInActivePng;
export const TabInventoryInActive = TabInventoryInActivePng;
export const TabHomeInActive = TabHomeInActivePng;
export const ProductSearchIcon = ProductSearchPng;
export const ShopDummyIcon = ShopDummyPng;
export const FashoIcon = FashoPng;
export const SalesPosIcon = SalesPosPng;
export const SalesNegIcon = SalesNegPng;
export const VisitorsIcon = VisitorsPng;
export const StarIcon = StarPng;
export const SettlementIcon = SettlementPng;
export const RefundIcon = RefundPng;
export const DangerIcon = DangerPng;
export const NotificationIcon = NotificationPng;
export const ProfileCircleIcon = ProfileCirclePng;
export const SuccessGif = Success_Gif;
export const DownwardGif = Downward_Gif;
